[package]
name = "example_electrum"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk_chain = { path = "../../crates/chain", features = ["serde"] }
bdk_electrum = { path = "../../crates/electrum" }
bdk_common = { path = "../../crates/common" }
example_cli = { path = "../example_cli" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
log = ["bdk_common/log"]
